#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
%define keepstatic 1
Name     : bc4
Version  : 4.4.0.25886
Release  : 21
URL      : file:///aot/build/clearlinux/packages/bc4/bc4-v4.4.0.25886.tar.gz
Source0  : file:///aot/build/clearlinux/packages/bc4/bc4-v4.4.0.25886.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSL-1.0 Zlib
Requires: bc4-bin = %{version}-%{release}
Requires: bc4-data = %{version}-%{release}
Requires: bc4-lib = %{version}-%{release}
BuildRequires : buildreq-cmake
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}
# Disable automatic requeriments processing
AutoReq: no

%description
Beyond Compare 4 for LINUX
Release Notes
CONTENTS
1) SUPPORTED FEATURES
2) REQUIREMENTS
3) INSTALLATION
4) CONTEXT MENUS
5) NOTES
6) Registering

%package bin
Summary: bin components for the bc4 package.
Group: Binaries
Requires: bc4-data = %{version}-%{release}
# Disable automatic requeriments processing
AutoReq: no

%description bin
bin components for the bc4 package.


%package data
Summary: data components for the bc4 package.
Group: Data
# Disable automatic requeriments processing
AutoReq: no

%description data
data components for the bc4 package.


%package lib
Summary: lib components for the bc4 package.
Group: Libraries
Requires: bc4-data = %{version}-%{release}
# Disable automatic requeriments processing
AutoReq: no

%description lib
lib components for the bc4 package.


%prep
%setup -q -n bc4
cd %{_builddir}/bc4

%build
unset http_proxy
unset https_proxy
unset no_proxy
export SSL_CERT_FILE=/var/cache/ca-certs/anchors/ca-certificates.crt
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1629322608
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
## altflags1 content
export CFLAGS="-g -O3 --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -floop-block -fno-math-errno -fno-semantic-interposition -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -funroll-loops -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=16 -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -ffat-lto-objects -fPIC -Wl,-z,max-page-size=0x1000 -fomit-frame-pointer -pthread -static-libstdc++ -static-libgcc -Wl,--build-id=sha1"
# -ffat-lto-objects -fno-PIE -fno-PIE -m64 -no-pie -fPIC -Wl,-z,max-page-size=0x1000 -fvisibility=hidden -flto-partition=none
# gcc: -feliminate-unused-debug-types -fipa-pta -flto=16 -Wno-error -Wp,-D_REENTRANT -fno-common
export CXXFLAGS="-g -O3 --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -floop-block -fno-math-errno -fno-semantic-interposition -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -funroll-loops -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=16 -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -fvisibility-inlines-hidden -pipe -ffat-lto-objects -fPIC -Wl,-z,max-page-size=0x1000 -fomit-frame-pointer -pthread -static-libstdc++ -static-libgcc -Wl,--build-id=sha1"
#
export FCFLAGS="-g -O3 --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -floop-block -fno-math-errno -fno-semantic-interposition -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -funroll-loops -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=16 -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -ffat-lto-objects -fPIC -Wl,-z,max-page-size=0x1000 -fomit-frame-pointer -pthread -static-libstdc++ -static-libgcc -Wl,--build-id=sha1"
export FFLAGS="-g -O3 --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -floop-block -fno-math-errno -fno-semantic-interposition -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -funroll-loops -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=16 -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -ffat-lto-objects -fPIC -Wl,-z,max-page-size=0x1000 -fomit-frame-pointer -Wl,--build-id=sha1"
export CFFLAGS="-g -O3 --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -floop-block -fno-math-errno -fno-semantic-interposition -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -funroll-loops -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=16 -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -ffat-lto-objects -fPIC -Wl,-z,max-page-size=0x1000 -fomit-frame-pointer -pthread -static-libstdc++ -static-libgcc -Wl,--build-id=sha1"
#
export LDFLAGS="-g -O3 --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -floop-block -fno-math-errno -fno-semantic-interposition -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -funroll-loops -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=16 -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -ffat-lto-objects -fPIC -Wl,-z,max-page-size=0x1000 -fomit-frame-pointer -pthread -static-libstdc++ -static-libgcc -lpthread -Wl,--build-id=sha1"
#
export AR=/usr/bin/gcc-ar
export RANLIB=/usr/bin/gcc-ranlib
export NM=/usr/bin/gcc-nm
#
export MAKEFLAGS=%{?_smp_mflags}
#
%global _lto_cflags 1
#global _lto_cflags %{nil}
%global _disable_maintainer_mode 1
#%global _disable_maintainer_mode %{nil}
#
export CCACHE_DISABLE=true
export PATH="/usr/lib64/ccache/bin:$PATH"
export CCACHE_NOHASHDIR=true
export CCACHE_CPP2=true
export CCACHE_SLOPPINESS=pch_defines,time_macros,locale,file_stat_matches,file_stat_matches_ctime,include_file_ctime,include_file_mtime,modules,system_headers,clang_index_store,file_macro
#export CCACHE_SLOPPINESS=modules,include_file_mtime,include_file_ctime,time_macros,pch_defines,file_stat_matches,clang_index_store,system_headers,locale
#export CCACHE_SLOPPINESS=pch_defines,time_macros,locale,clang_index_store,file_macro
export CCACHE_DIR=/var/tmp/ccache
export CCACHE_BASEDIR=/builddir/build/BUILD
#export CCACHE_LOGFILE=/var/tmp/ccache/cache.debug
#export CCACHE_DEBUG=true
#export CCACHE_NODIRECT=true
## altflags1 end
%cmake ..
make  %{?_smp_mflags}    V=1 VERBOSE=1
popd

%install
export SOURCE_DATE_EPOCH=1629322608
rm -rf %{buildroot}
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/bcompare

%files data
%defattr(-,root,root,-)
/usr/share/applications/bcompare.desktop
/usr/share/mime-packages/bcompare.xml
/usr/share/pixmaps/bcompare.png
/usr/share/pixmaps/bcomparefull32.png
/usr/share/pixmaps/bcomparehalf32.png

%files lib
%defattr(-,root,root,-)
/usr/lib64/beyondcompare/BC4Key.txt
/usr/lib64/beyondcompare/BCompare
/usr/lib64/beyondcompare/BCompare.mad
/usr/lib64/beyondcompare/README
/usr/lib64/beyondcompare/RPM-GPG-KEY-scootersoftware
/usr/lib64/beyondcompare/bcmount.sh
/usr/lib64/beyondcompare/bcmount32
/usr/lib64/beyondcompare/bcmount64
/usr/lib64/beyondcompare/ext/bcompare-ext-caja.amd64.so
/usr/lib64/beyondcompare/ext/bcompare-ext-caja.i386.so
/usr/lib64/beyondcompare/ext/bcompare-ext-nautilus.amd64.so
/usr/lib64/beyondcompare/ext/bcompare-ext-nautilus.i386.so
/usr/lib64/beyondcompare/ext/bcompare-ext-nemo.amd64.so
/usr/lib64/beyondcompare/ext/bcompare-ext-nemo.i386.so
/usr/lib64/beyondcompare/ext/bcompare-ext-thunarx-2.amd64.so
/usr/lib64/beyondcompare/ext/bcompare-ext-thunarx-2.i386.so
/usr/lib64/beyondcompare/ext/bcompare-ext-thunarx-3.amd64.so
/usr/lib64/beyondcompare/ext/bcompare-ext-thunarx-3.i386.so
/usr/lib64/beyondcompare/ext/bcompare_ext_kde.amd64.so
/usr/lib64/beyondcompare/ext/bcompare_ext_kde.desktop
/usr/lib64/beyondcompare/ext/bcompare_ext_kde.i386.so
/usr/lib64/beyondcompare/ext/bcompare_ext_kde5.amd64.so
/usr/lib64/beyondcompare/ext/bcompare_ext_kde5.i386.so
/usr/lib64/beyondcompare/ext/bcompare_ext_konq.amd64.so
/usr/lib64/beyondcompare/ext/bcompare_ext_konq.desktop
/usr/lib64/beyondcompare/ext/bcompare_ext_konq.i386.so
/usr/lib64/beyondcompare/help/3-way_merge_concepts.html
/usr/lib64/beyondcompare/help/accept.png
/usr/lib64/beyondcompare/help/archive_files.html
/usr/lib64/beyondcompare/help/bcclipmain.html
/usr/lib64/beyondcompare/help/bcclipmain.png
/usr/lib64/beyondcompare/help/bcclipmain_zoom57.jpg
/usr/lib64/beyondcompare/help/bcclipoptions.html
/usr/lib64/beyondcompare/help/bcclipsystemtray.png
/usr/lib64/beyondcompare/help/bclogo.png
/usr/lib64/beyondcompare/help/browse.png
/usr/lib64/beyondcompare/help/calling_bc_from_other_applications.html
/usr/lib64/beyondcompare/help/cicon1.png
/usr/lib64/beyondcompare/help/cicon2.png
/usr/lib64/beyondcompare/help/cicon9.png
/usr/lib64/beyondcompare/help/cicon_loadindex_ani.gif
/usr/lib64/beyondcompare/help/ciconidx.gif
/usr/lib64/beyondcompare/help/collapseall.png
/usr/lib64/beyondcompare/help/command_line_reference.html
/usr/lib64/beyondcompare/help/commands_reference.html
/usr/lib64/beyondcompare/help/commandsbc.html
/usr/lib64/beyondcompare/help/commandsdata.html
/usr/lib64/beyondcompare/help/commandsdir.html
/usr/lib64/beyondcompare/help/commandsdirmerge.html
/usr/lib64/beyondcompare/help/commandsdirsync.html
/usr/lib64/beyondcompare/help/commandshex.html
/usr/lib64/beyondcompare/help/commandshome.html
/usr/lib64/beyondcompare/help/commandsmp3.html
/usr/lib64/beyondcompare/help/commandspix.html
/usr/lib64/beyondcompare/help/commandsreg.html
/usr/lib64/beyondcompare/help/commandstext.html
/usr/lib64/beyondcompare/help/commandstextedit.html
/usr/lib64/beyondcompare/help/commandstextmerge.html
/usr/lib64/beyondcompare/help/commandstextpatch.html
/usr/lib64/beyondcompare/help/commandsver.html
/usr/lib64/beyondcompare/help/compare.png
/usr/lib64/beyondcompare/help/conflict.png
/usr/lib64/beyondcompare/help/conflictsectionnext.png
/usr/lib64/beyondcompare/help/conflictsectionoffnext.png
/usr/lib64/beyondcompare/help/conflictsectionprev.png
/usr/lib64/beyondcompare/help/contentconflict.png
/usr/lib64/beyondcompare/help/contentcopycentertooutput.png
/usr/lib64/beyondcompare/help/contentcopyleft.png
/usr/lib64/beyondcompare/help/contentcopylefttooutput.png
/usr/lib64/beyondcompare/help/contentcopyright.png
/usr/lib64/beyondcompare/help/contentcopyrighttooutput.png
/usr/lib64/beyondcompare/help/contentdeleteleft.png
/usr/lib64/beyondcompare/help/contentdeleteright.png
/usr/lib64/beyondcompare/help/contentdifferent.png
/usr/lib64/beyondcompare/help/contentdifferentbinary.png
/usr/lib64/beyondcompare/help/contentmergeable.png
/usr/lib64/beyondcompare/help/contentmerged.png
/usr/lib64/beyondcompare/help/contentsame.png
/usr/lib64/beyondcompare/help/contentsamebinary.png
/usr/lib64/beyondcompare/help/contentsimilar.png
/usr/lib64/beyondcompare/help/copy.png
/usr/lib64/beyondcompare/help/copyfileleft.png
/usr/lib64/beyondcompare/help/copyfileright.png
/usr/lib64/beyondcompare/help/copyleft.png
/usr/lib64/beyondcompare/help/copyleftorright.png
/usr/lib64/beyondcompare/help/copyright.png
/usr/lib64/beyondcompare/help/copyto.png
/usr/lib64/beyondcompare/help/copytooutput.png
/usr/lib64/beyondcompare/help/default.css
/usr/lib64/beyondcompare/help/delete.png
/usr/lib64/beyondcompare/help/difffilenext.png
/usr/lib64/beyondcompare/help/difffileprev.png
/usr/lib64/beyondcompare/help/dir_filtering_the_view.html
/usr/lib64/beyondcompare/help/dir_how_to_compare.html
/usr/lib64/beyondcompare/help/dir_merge_understanding_the_display.html
/usr/lib64/beyondcompare/help/dir_reconciling_differences.html
/usr/lib64/beyondcompare/help/dir_sync_how_to_sync.html
/usr/lib64/beyondcompare/help/dir_sync_understanding_the_display.html
/usr/lib64/beyondcompare/help/dir_understanding_the_display.html
/usr/lib64/beyondcompare/help/dircomparefilesonly.png
/usr/lib64/beyondcompare/help/dircomparesession.png
/usr/lib64/beyondcompare/help/dircomparestructure.png
/usr/lib64/beyondcompare/help/dirdisplayarchive.png
/usr/lib64/beyondcompare/help/dirdisplaydir.png
/usr/lib64/beyondcompare/help/dirdisplayex.png
/usr/lib64/beyondcompare/help/dirdisplayfile.png
/usr/lib64/beyondcompare/help/dirfavconflict.png
/usr/lib64/beyondcompare/help/dirfavdiffnoorphan.png
/usr/lib64/beyondcompare/help/dirfavleft.png
/usr/lib64/beyondcompare/help/dirfavleftnewer.png
/usr/lib64/beyondcompare/help/dirfavleftnewerorphan.png
/usr/lib64/beyondcompare/help/dirfavleftorphan.png
/usr/lib64/beyondcompare/help/dirfavmergeable.png
/usr/lib64/beyondcompare/help/dirfavnoorphan.png
/usr/lib64/beyondcompare/help/dirfavorphan.png
/usr/lib64/beyondcompare/help/dirfavright.png
/usr/lib64/beyondcompare/help/dirfavrightnewer.png
/usr/lib64/beyondcompare/help/dirfavrightnewerorphan.png
/usr/lib64/beyondcompare/help/dirfavrightorphan.png
/usr/lib64/beyondcompare/help/dirflatten.png
/usr/lib64/beyondcompare/help/dirmerge.png
/usr/lib64/beyondcompare/help/dirmergesession.png
/usr/lib64/beyondcompare/help/dirshowall.png
/usr/lib64/beyondcompare/help/dirsyncsession.png
/usr/lib64/beyondcompare/help/display_filters.html
/usr/lib64/beyondcompare/help/displayfont.png
/usr/lib64/beyondcompare/help/displayfontdecrease.png
/usr/lib64/beyondcompare/help/displayfontincrease.png
/usr/lib64/beyondcompare/help/displayfontreset.png
/usr/lib64/beyondcompare/help/dlgbrowsemachine.html
/usr/lib64/beyondcompare/help/dlgdatacolhandling.html
/usr/lib64/beyondcompare/help/dlgdiralignwithitem.html
/usr/lib64/beyondcompare/help/dlgdirfind.html
/usr/lib64/beyondcompare/help/dlgdirotherfilteritem.html
/usr/lib64/beyondcompare/help/dlgexport.html
/usr/lib64/beyondcompare/help/dlgfileformatmanager.html
/usr/lib64/beyondcompare/help/dlgimport.html
/usr/lib64/beyondcompare/help/dlgnag.html
/usr/lib64/beyondcompare/help/dlgopenwithitem.html
/usr/lib64/beyondcompare/help/dlgprofilebrowse.html
/usr/lib64/beyondcompare/help/dlgprofilemanager.html
/usr/lib64/beyondcompare/help/dlgprogoptions.html
/usr/lib64/beyondcompare/help/dlgregister.html
/usr/lib64/beyondcompare/help/dlgreport.html
/usr/lib64/beyondcompare/help/dlgrestore.html
/usr/lib64/beyondcompare/help/dlgsnapshot.html
/usr/lib64/beyondcompare/help/dlgsourcecontrolmanager.html
/usr/lib64/beyondcompare/help/dlgsupport.html
/usr/lib64/beyondcompare/help/dlgtextfindinfiles.html
/usr/lib64/beyondcompare/help/dlgtextgrammaritem.html
/usr/lib64/beyondcompare/help/dlgtextreplacementitem.html
/usr/lib64/beyondcompare/help/dlgworkspacemanager.html
/usr/lib64/beyondcompare/help/down.png
/usr/lib64/beyondcompare/help/dropdown.png
/usr/lib64/beyondcompare/help/editing_text.html
/usr/lib64/beyondcompare/help/expandall.png
/usr/lib64/beyondcompare/help/favall.png
/usr/lib64/beyondcompare/help/favdiff.png
/usr/lib64/beyondcompare/help/favnone.png
/usr/lib64/beyondcompare/help/favorleft.png
/usr/lib64/beyondcompare/help/favorright.png
/usr/lib64/beyondcompare/help/favsame.png
/usr/lib64/beyondcompare/help/file_formats.html
/usr/lib64/beyondcompare/help/file_masks.html
/usr/lib64/beyondcompare/help/filecopyselright.png
/usr/lib64/beyondcompare/help/filefavconflict.png
/usr/lib64/beyondcompare/help/filefavleft.png
/usr/lib64/beyondcompare/help/filefavmergeable.png
/usr/lib64/beyondcompare/help/filefavright.png
/usr/lib64/beyondcompare/help/fileformatmanager.png
/usr/lib64/beyondcompare/help/filetakesectioncenter.png
/usr/lib64/beyondcompare/help/filetakesectionleft.png
/usr/lib64/beyondcompare/help/filetakesectionright.png
/usr/lib64/beyondcompare/help/filteredlinecount.png
/usr/lib64/beyondcompare/help/filters.png
/usr/lib64/beyondcompare/help/find.png
/usr/lib64/beyondcompare/help/findinfiles.png
/usr/lib64/beyondcompare/help/findnext.png
/usr/lib64/beyondcompare/help/findprev.png
/usr/lib64/beyondcompare/help/formatdata.html
/usr/lib64/beyondcompare/help/formatdataconversion.html
/usr/lib64/beyondcompare/help/formatdatageneral.html
/usr/lib64/beyondcompare/help/formatdataregional.html
/usr/lib64/beyondcompare/help/formatdatatype.html
/usr/lib64/beyondcompare/help/formatexternalgeneral.html
/usr/lib64/beyondcompare/help/formathex.html
/usr/lib64/beyondcompare/help/formathexconversion.html
/usr/lib64/beyondcompare/help/formathexgeneral.html
/usr/lib64/beyondcompare/help/formatpix.html
/usr/lib64/beyondcompare/help/formatpixconversion.html
/usr/lib64/beyondcompare/help/formatpixgeneral.html
/usr/lib64/beyondcompare/help/formattext.html
/usr/lib64/beyondcompare/help/formattextconversion.html
/usr/lib64/beyondcompare/help/formattextgeneral.html
/usr/lib64/beyondcompare/help/formattextgrammar.html
/usr/lib64/beyondcompare/help/formattextmisc.html
/usr/lib64/beyondcompare/help/fulledit.png
/usr/lib64/beyondcompare/help/fullrefresh.png
/usr/lib64/beyondcompare/help/fullscreen.png
/usr/lib64/beyondcompare/help/glossary.html
/usr/lib64/beyondcompare/help/goto.png
/usr/lib64/beyondcompare/help/grammars.html
/usr/lib64/beyondcompare/help/headerkey.png
/usr/lib64/beyondcompare/help/helpcontents.png
/usr/lib64/beyondcompare/help/helpman_navigation.js
/usr/lib64/beyondcompare/help/helpman_settings.js
/usr/lib64/beyondcompare/help/helpman_topicinit.js
/usr/lib64/beyondcompare/help/highlight.js
/usr/lib64/beyondcompare/help/hmcontent.html
/usr/lib64/beyondcompare/help/hmcontextids.js
/usr/lib64/beyondcompare/help/hmftsearch.html
/usr/lib64/beyondcompare/help/hmkwindex.html
/usr/lib64/beyondcompare/help/ignored.png
/usr/lib64/beyondcompare/help/index.html
/usr/lib64/beyondcompare/help/info.png
/usr/lib64/beyondcompare/help/insigignored.png
/usr/lib64/beyondcompare/help/jquery.js
/usr/lib64/beyondcompare/help/license_agreement.html
/usr/lib64/beyondcompare/help/license_agreement_7-zip.html
/usr/lib64/beyondcompare/help/license_agreement_fpc.html
/usr/lib64/beyondcompare/help/license_agreement_gpl3.html
/usr/lib64/beyondcompare/help/license_agreement_htmlviewer.html
/usr/lib64/beyondcompare/help/license_agreement_httpget.html
/usr/lib64/beyondcompare/help/license_agreement_innosetup.html
/usr/lib64/beyondcompare/help/license_agreement_intlck64.html
/usr/lib64/beyondcompare/help/license_agreement_lgpl.html
/usr/lib64/beyondcompare/help/license_agreement_mpl.html
/usr/lib64/beyondcompare/help/license_agreement_pcre.html
/usr/lib64/beyondcompare/help/license_agreement_regexpr.html
/usr/lib64/beyondcompare/help/license_agreement_textdiff.html
/usr/lib64/beyondcompare/help/license_agreement_wavpack.html
/usr/lib64/beyondcompare/help/license_agreement_wix.html
/usr/lib64/beyondcompare/help/license_agreement_zlib.html
/usr/lib64/beyondcompare/help/linux.png
/usr/lib64/beyondcompare/help/mac.png
/usr/lib64/beyondcompare/help/maclineending.png
/usr/lib64/beyondcompare/help/managing_sessions.html
/usr/lib64/beyondcompare/help/mergebase.png
/usr/lib64/beyondcompare/help/mergenobase.png
/usr/lib64/beyondcompare/help/mirrorleft.png
/usr/lib64/beyondcompare/help/mirrorright.png
/usr/lib64/beyondcompare/help/moveboth.png
/usr/lib64/beyondcompare/help/moveleftorright.png
/usr/lib64/beyondcompare/help/moveright.png
/usr/lib64/beyondcompare/help/moveto.png
/usr/lib64/beyondcompare/help/moving_bc_to_another_computer.html
/usr/lib64/beyondcompare/help/mp3play.png
/usr/lib64/beyondcompare/help/mp3play2.png
/usr/lib64/beyondcompare/help/newfolder.png
/usr/lib64/beyondcompare/help/next-dis.png
/usr/lib64/beyondcompare/help/next-hot.png
/usr/lib64/beyondcompare/help/next.png
/usr/lib64/beyondcompare/help/note.png
/usr/lib64/beyondcompare/help/opattrib.html
/usr/lib64/beyondcompare/help/opcompare.html
/usr/lib64/beyondcompare/help/opcopy.html
/usr/lib64/beyondcompare/help/opcopyto.html
/usr/lib64/beyondcompare/help/opcopytooutput.html
/usr/lib64/beyondcompare/help/opdelete.html
/usr/lib64/beyondcompare/help/opexchange.html
/usr/lib64/beyondcompare/help/opexclude.html
/usr/lib64/beyondcompare/help/opmerge.html
/usr/lib64/beyondcompare/help/opmove.html
/usr/lib64/beyondcompare/help/opmoveto.html
/usr/lib64/beyondcompare/help/opnewfolder.html
/usr/lib64/beyondcompare/help/oprename.html
/usr/lib64/beyondcompare/help/opsync.html
/usr/lib64/beyondcompare/help/options.png
/usr/lib64/beyondcompare/help/optionsarchive.html
/usr/lib64/beyondcompare/help/optionsbackup.html
/usr/lib64/beyondcompare/help/optionscolor.html
/usr/lib64/beyondcompare/help/optionscommand.html
/usr/lib64/beyondcompare/help/optionsdircolor.html
/usr/lib64/beyondcompare/help/optionsfilecolor.html
/usr/lib64/beyondcompare/help/optionsnextdiff.html
/usr/lib64/beyondcompare/help/optionsop.html
/usr/lib64/beyondcompare/help/optionsopenwith.html
/usr/lib64/beyondcompare/help/optionspixcolor.html
/usr/lib64/beyondcompare/help/optionsstartup.html
/usr/lib64/beyondcompare/help/optionstab.html
/usr/lib64/beyondcompare/help/optionstext.html
/usr/lib64/beyondcompare/help/optionstweak.html
/usr/lib64/beyondcompare/help/optouch.html
/usr/lib64/beyondcompare/help/outputwindow.png
/usr/lib64/beyondcompare/help/overunder.png
/usr/lib64/beyondcompare/help/pin.png
/usr/lib64/beyondcompare/help/pix_how_to_compare.html
/usr/lib64/beyondcompare/help/pixautoscale.png
/usr/lib64/beyondcompare/help/pixblendtoggle.png
/usr/lib64/beyondcompare/help/pixcomparetags.png
/usr/lib64/beyondcompare/help/pixdiffblend.png
/usr/lib64/beyondcompare/help/pixdiffrange.png
/usr/lib64/beyondcompare/help/pixdifftolerance.png
/usr/lib64/beyondcompare/help/pixfliphorz.png
/usr/lib64/beyondcompare/help/pixflipvert.png
/usr/lib64/beyondcompare/help/pixrotateleft.png
/usr/lib64/beyondcompare/help/pixrotateright.png
/usr/lib64/beyondcompare/help/pixzoomactual.png
/usr/lib64/beyondcompare/help/pixzoomfit.png
/usr/lib64/beyondcompare/help/prefsinterface.png
/usr/lib64/beyondcompare/help/prev-dis.png
/usr/lib64/beyondcompare/help/prev-hot.png
/usr/lib64/beyondcompare/help/prev.png
/usr/lib64/beyondcompare/help/pro.png
/usr/lib64/beyondcompare/help/profileamazons3.html
/usr/lib64/beyondcompare/help/profiledropbox.html
/usr/lib64/beyondcompare/help/profileftp.html
/usr/lib64/beyondcompare/help/profileftpconnection.html
/usr/lib64/beyondcompare/help/profileftpglobal.html
/usr/lib64/beyondcompare/help/profileftplisting.html
/usr/lib64/beyondcompare/help/profileftplogin.html
/usr/lib64/beyondcompare/help/profileftpproxy.html
/usr/lib64/beyondcompare/help/profileftpserver.html
/usr/lib64/beyondcompare/help/profileftptransfer.html
/usr/lib64/beyondcompare/help/profileonedrive.html
/usr/lib64/beyondcompare/help/profilesvn.html
/usr/lib64/beyondcompare/help/profilewebdav.html
/usr/lib64/beyondcompare/help/recompare.png
/usr/lib64/beyondcompare/help/red-bg.jpg
/usr/lib64/beyondcompare/help/redo.png
/usr/lib64/beyondcompare/help/refresh.png
/usr/lib64/beyondcompare/help/regular_expression_reference.html
/usr/lib64/beyondcompare/help/remote_services.html
/usr/lib64/beyondcompare/help/rename.png
/usr/lib64/beyondcompare/help/replace.png
/usr/lib64/beyondcompare/help/report.png
/usr/lib64/beyondcompare/help/rules.png
/usr/lib64/beyondcompare/help/rules_vs_file_formats.html
/usr/lib64/beyondcompare/help/rulesvsformats.png
/usr/lib64/beyondcompare/help/sample_regular_expressions.html
/usr/lib64/beyondcompare/help/sample_scripts.html
/usr/lib64/beyondcompare/help/save.png
/usr/lib64/beyondcompare/help/savesnapshot.png
/usr/lib64/beyondcompare/help/scheduling_a_script.html
/usr/lib64/beyondcompare/help/scripting_reference.html
/usr/lib64/beyondcompare/help/scripts.html
/usr/lib64/beyondcompare/help/searchedit.png
/usr/lib64/beyondcompare/help/searching_for_text.html
/usr/lib64/beyondcompare/help/selectall.png
/usr/lib64/beyondcompare/help/selectallfiles.png
/usr/lib64/beyondcompare/help/session_settings.html
/usr/lib64/beyondcompare/help/sessiondata.html
/usr/lib64/beyondcompare/help/sessiondataalignment.html
/usr/lib64/beyondcompare/help/sessiondatacolumns.html
/usr/lib64/beyondcompare/help/sessiondataformats.html
/usr/lib64/beyondcompare/help/sessiondataspecs.html
/usr/lib64/beyondcompare/help/sessiondir.html
/usr/lib64/beyondcompare/help/sessiondircomparison.html
/usr/lib64/beyondcompare/help/sessiondirhandling.html
/usr/lib64/beyondcompare/help/sessiondirmerge.html
/usr/lib64/beyondcompare/help/sessiondirmergecomparison.html
/usr/lib64/beyondcompare/help/sessiondirmergehandling.html
/usr/lib64/beyondcompare/help/sessiondirmergemisc.html
/usr/lib64/beyondcompare/help/sessiondirmergenamefilter.html
/usr/lib64/beyondcompare/help/sessiondirmergeotherfilters.html
/usr/lib64/beyondcompare/help/sessiondirmergespecs.html
/usr/lib64/beyondcompare/help/sessiondirmisc.html
/usr/lib64/beyondcompare/help/sessiondirnamefilter.html
/usr/lib64/beyondcompare/help/sessiondirotherfilters.html
/usr/lib64/beyondcompare/help/sessiondirspecs.html
/usr/lib64/beyondcompare/help/sessiondirsync.html
/usr/lib64/beyondcompare/help/sessiondirsynccomparison.html
/usr/lib64/beyondcompare/help/sessiondirsynchandling.html
/usr/lib64/beyondcompare/help/sessiondirsyncmisc.html
/usr/lib64/beyondcompare/help/sessiondirsyncnamefilter.html
/usr/lib64/beyondcompare/help/sessiondirsyncops.html
/usr/lib64/beyondcompare/help/sessiondirsyncotherfilters.html
/usr/lib64/beyondcompare/help/sessiondirsyncspecs.html
/usr/lib64/beyondcompare/help/sessionedit.png
/usr/lib64/beyondcompare/help/sessionhex.html
/usr/lib64/beyondcompare/help/sessionhexcomparison.html
/usr/lib64/beyondcompare/help/sessionhexformats.html
/usr/lib64/beyondcompare/help/sessionhexspecs.html
/usr/lib64/beyondcompare/help/sessionlocked.png
/usr/lib64/beyondcompare/help/sessionmp3.html
/usr/lib64/beyondcompare/help/sessionmp3importance.html
/usr/lib64/beyondcompare/help/sessionmp3specs.html
/usr/lib64/beyondcompare/help/sessionpix.html
/usr/lib64/beyondcompare/help/sessionpixformats.html
/usr/lib64/beyondcompare/help/sessionpixreplacements.html
/usr/lib64/beyondcompare/help/sessionpixspecs.html
/usr/lib64/beyondcompare/help/sessionreg.html
/usr/lib64/beyondcompare/help/sessionregspecs.html
/usr/lib64/beyondcompare/help/sessionsave.png
/usr/lib64/beyondcompare/help/sessionsaveas.png
/usr/lib64/beyondcompare/help/sessiontext.html
/usr/lib64/beyondcompare/help/sessiontextalignment.html
/usr/lib64/beyondcompare/help/sessiontextformats.html
/usr/lib64/beyondcompare/help/sessiontextimportance.html
/usr/lib64/beyondcompare/help/sessiontextmerge.html
/usr/lib64/beyondcompare/help/sessiontextmergealignment.html
/usr/lib64/beyondcompare/help/sessiontextmergeformats.html
/usr/lib64/beyondcompare/help/sessiontextmergeimportance.html
/usr/lib64/beyondcompare/help/sessiontextmergespecs.html
/usr/lib64/beyondcompare/help/sessiontextreplacements.html
/usr/lib64/beyondcompare/help/sessiontextspecs.html
/usr/lib64/beyondcompare/help/sessionver.html
/usr/lib64/beyondcompare/help/sessionverimportance.html
/usr/lib64/beyondcompare/help/sessionverspecs.html
/usr/lib64/beyondcompare/help/settings.js
/usr/lib64/beyondcompare/help/settings_reference.html
/usr/lib64/beyondcompare/help/sharedsessions.png
/usr/lib64/beyondcompare/help/sharing_sessions.html
/usr/lib64/beyondcompare/help/showaligndetails.png
/usr/lib64/beyondcompare/help/showcenter.png
/usr/lib64/beyondcompare/help/showcontext.png
/usr/lib64/beyondcompare/help/showhexdetails.png
/usr/lib64/beyondcompare/help/showitemnum.png
/usr/lib64/beyondcompare/help/showruler.png
/usr/lib64/beyondcompare/help/showsyntaxhighlighting.png
/usr/lib64/beyondcompare/help/showtextdetails.png
/usr/lib64/beyondcompare/help/showthumbnail.png
/usr/lib64/beyondcompare/help/showws.png
/usr/lib64/beyondcompare/help/sidebyside.png
/usr/lib64/beyondcompare/help/snapshots.html
/usr/lib64/beyondcompare/help/space.png
/usr/lib64/beyondcompare/help/specs.html
/usr/lib64/beyondcompare/help/specsback.png
/usr/lib64/beyondcompare/help/specsforward.png
/usr/lib64/beyondcompare/help/standard_vs_pro.html
/usr/lib64/beyondcompare/help/support_ordering_and_license.html
/usr/lib64/beyondcompare/help/suppressfilters.png
/usr/lib64/beyondcompare/help/swap.png
/usr/lib64/beyondcompare/help/synccopydeleteleft.png
/usr/lib64/beyondcompare/help/synccopydeleteright.png
/usr/lib64/beyondcompare/help/synccopyleft.png
/usr/lib64/beyondcompare/help/synccopyright.png
/usr/lib64/beyondcompare/help/syncdelete.png
/usr/lib64/beyondcompare/help/syncprompt.png
/usr/lib64/beyondcompare/help/syncrun.png
/usr/lib64/beyondcompare/help/tab.png
/usr/lib64/beyondcompare/help/texteditsession.png
/usr/lib64/beyondcompare/help/textmergesession.png
/usr/lib64/beyondcompare/help/textpatchsession.png
/usr/lib64/beyondcompare/help/todir.png
/usr/lib64/beyondcompare/help/todirflatten.png
/usr/lib64/beyondcompare/help/todirkeepbase.png
/usr/lib64/beyondcompare/help/todirkeeprelative.png
/usr/lib64/beyondcompare/help/toolbardropdown.png
/usr/lib64/beyondcompare/help/toolbarfavorites.png
/usr/lib64/beyondcompare/help/toolbarfilefilters.png
/usr/lib64/beyondcompare/help/toolbartoggles.png
/usr/lib64/beyondcompare/help/top-hot.png
/usr/lib64/beyondcompare/help/top.png
/usr/lib64/beyondcompare/help/touch.png
/usr/lib64/beyondcompare/help/undo.png
/usr/lib64/beyondcompare/help/unixlineending.png
/usr/lib64/beyondcompare/help/up.png
/usr/lib64/beyondcompare/help/updateboth.png
/usr/lib64/beyondcompare/help/updateleft.png
/usr/lib64/beyondcompare/help/updateright.png
/usr/lib64/beyondcompare/help/uponelevel.png
/usr/lib64/beyondcompare/help/using_bc.html
/usr/lib64/beyondcompare/help/using_text_merge.html
/usr/lib64/beyondcompare/help/viewdata.html
/usr/lib64/beyondcompare/help/viewdata.jpg
/usr/lib64/beyondcompare/help/viewdata_zoom33.jpg
/usr/lib64/beyondcompare/help/viewdir.html
/usr/lib64/beyondcompare/help/viewdir.jpg
/usr/lib64/beyondcompare/help/viewdir_zoom33.jpg
/usr/lib64/beyondcompare/help/viewdirmerge.html
/usr/lib64/beyondcompare/help/viewdirmerge.jpg
/usr/lib64/beyondcompare/help/viewdirmerge_zoom33.jpg
/usr/lib64/beyondcompare/help/viewdirsync.html
/usr/lib64/beyondcompare/help/viewdirsync.jpg
/usr/lib64/beyondcompare/help/viewdirsync_zoom33.jpg
/usr/lib64/beyondcompare/help/viewhex.html
/usr/lib64/beyondcompare/help/viewhex.jpg
/usr/lib64/beyondcompare/help/viewhex_zoom33.jpg
/usr/lib64/beyondcompare/help/viewhome.html
/usr/lib64/beyondcompare/help/viewhome.jpg
/usr/lib64/beyondcompare/help/viewhome_zoom33.jpg
/usr/lib64/beyondcompare/help/viewmp3.jpg
/usr/lib64/beyondcompare/help/viewmp3_zoom33.jpg
/usr/lib64/beyondcompare/help/viewother.html
/usr/lib64/beyondcompare/help/viewpix.html
/usr/lib64/beyondcompare/help/viewpix.jpg
/usr/lib64/beyondcompare/help/viewpix_zoom33.jpg
/usr/lib64/beyondcompare/help/viewreg.html
/usr/lib64/beyondcompare/help/viewreg.jpg
/usr/lib64/beyondcompare/help/viewreg_zoom33.jpg
/usr/lib64/beyondcompare/help/viewtext.html
/usr/lib64/beyondcompare/help/viewtext.jpg
/usr/lib64/beyondcompare/help/viewtext_zoom33.jpg
/usr/lib64/beyondcompare/help/viewtextedit.html
/usr/lib64/beyondcompare/help/viewtextedit.jpg
/usr/lib64/beyondcompare/help/viewtextedit_zoom33.jpg
/usr/lib64/beyondcompare/help/viewtextmerge.html
/usr/lib64/beyondcompare/help/viewtextmerge.jpg
/usr/lib64/beyondcompare/help/viewtextmerge_zoom33.jpg
/usr/lib64/beyondcompare/help/viewtextpatch.html
/usr/lib64/beyondcompare/help/viewtextpatch.jpg
/usr/lib64/beyondcompare/help/viewtextpatch_zoom33.jpg
/usr/lib64/beyondcompare/help/viewver.jpg
/usr/lib64/beyondcompare/help/viewver_zoom33.jpg
/usr/lib64/beyondcompare/help/walking_through_differences.html
/usr/lib64/beyondcompare/help/warning.png
/usr/lib64/beyondcompare/help/webbrowser.png
/usr/lib64/beyondcompare/help/welcome.html
/usr/lib64/beyondcompare/help/whats_new.html
/usr/lib64/beyondcompare/help/where_settings_are_stored.html
/usr/lib64/beyondcompare/help/windows.png
/usr/lib64/beyondcompare/help/windowslineending.png
/usr/lib64/beyondcompare/help/zoom_index.js
/usr/lib64/beyondcompare/help/zoom_pageinfo.js
/usr/lib64/beyondcompare/help/zoom_search.js
/usr/lib64/beyondcompare/help/zoomin.png
/usr/lib64/beyondcompare/help/zoomout.png
/usr/lib64/beyondcompare/kde_context_menu
/usr/lib64/beyondcompare/lib7z.so
/usr/lib64/beyondcompare/libQt4Pas.so.5
/usr/lib64/beyondcompare/libunrar.so
/usr/lib64/beyondcompare/mime.types
/usr/lib64/beyondcompare/qt4/libQtCore.so.4
/usr/lib64/beyondcompare/qt4/libQtGui.so.4
/usr/lib64/beyondcompare/scootersoftware.repo
